#
name: Publish

on:
  push:
    tags:
      - "v*.*.*"

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_VERSION: 7.0.400
  CONTAINER_NAME: complete-information-household-backend

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  publish:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Prepare variables for run
        id: tag_name
        run: |
          if [[ ${GITHUB_REF} == *"-"* ]]; then
            RTAG=Unreleased
          else
            RTAG=${GITHUB_REF#refs/tags/v}
          fi
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
          echo ::set-output name=release_tag::$RTAG
        shell: bash
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.release_tag }}
          path: ./backend/CHANGELOG.md
      - name: Build and Publish Image
        run: dotnet run --project ./backend publish ${{ steps.tag_name.outputs.current_version }} "${{ env.REGISTRY }}" "${OWNER,,}"
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
